name: Build .deb Package

on:
  push:
    tags:
      - 'v*' # Trigger on version tags
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Build Go binary from main/main.go
        run: |
          # Build for Linux amd64 - specifying the main.go path
          GOOS=linux GOARCH=amd64 go build -o myapp ./main

          # Verify binary was built
          file myapp
          ls -la myapp

      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Create Debian package structure
        run: |
          # Create package directory structure
          mkdir -p myapp-deb/DEBIAN
          mkdir -p myapp-deb/usr/local/bin
          mkdir -p myapp-deb/etc/myapp
          mkdir -p myapp-deb/lib/systemd/system

          # Copy binary
          cp myapp myapp-deb/usr/local/bin/

          # Copy configuration if it exists (adjust path as needed)
          [ -f config/config.yaml ] && cp config/config.yaml myapp-deb/etc/myapp/ || echo "No config file found"

          # Create systemd service file
          cat > myapp-deb/lib/systemd/system/myapp.service << 'EOF'
          [Unit]
          Description=My Go Application
          After=network.target

          [Service]
          Type=simple
          User=myapp
          Group=myapp
          ExecStart=/usr/local/bin/myapp
          Restart=always
          WorkingDirectory=/opt/myapp
          EnvironmentFile=-/etc/myapp/config.yaml

          [Install]
          WantedBy=multi-user.target
          EOF

      - name: Create control file
        run: |
          # Extract version from tag or use default
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
          else
            VERSION="0.0.1-${GITHUB_SHA::7}"
          fi

          cat > myapp-deb/DEBIAN/control << EOF
          Package: myapp
          Version: ${VERSION}
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: libc6 (>= 2.31)
          Maintainer: ${GITHUB_REPOSITORY_OWNER} <${GITHUB_REPOSITORY_OWNER}@users.noreply.github.com>
          Homepage: https://github.com/${{ github.repository }}
          Description: My Go Application
           A Go application built from main/main.go
           This package was automatically built via GitHub Actions.
          EOF

      - name: Create postinst script
        run: |
          cat > myapp-deb/DEBIAN/postinst << 'EOF'
          #!/bin/bash
          set -e

          # Create application directory
          mkdir -p /opt/myapp

          # Create user if it doesn't exist
          if ! id -u myapp > /dev/null 2>&1; then
              useradd --system --no-create-home --shell /usr/sbin/nologin myapp
          fi

          # Set permissions
          chown -R myapp:myapp /etc/myapp 2>/dev/null || true
          chown myapp:myapp /usr/local/bin/myapp
          chown -R myapp:myapp /opt/myapp

          # Enable and start service
          if [ -f /lib/systemd/system/myapp.service ]; then
              systemctl daemon-reload
              systemctl enable myapp.service
              systemctl start myapp.service || echo "Service started manually"
          fi

          echo "myapp installation completed successfully"
          exit 0
          EOF
          chmod 755 myapp-deb/DEBIAN/postinst

      - name: Create prerm script
        run: |
          cat > myapp-deb/DEBIAN/prerm << 'EOF'
          #!/bin/bash
          set -e

          # Stop service before removal
          if systemctl is-active --quiet myapp.service 2>/dev/null; then
              systemctl stop myapp.service
              systemctl disable myapp.service
          fi

          exit 0
          EOF
          chmod 755 myapp-deb/DEBIAN/prerm

      - name: Set proper permissions
        run: |
          # Set directory permissions
          find myapp-deb -type d -exec chmod 755 {} \;

          # Set file permissions
          find myapp-deb -type f -not -path "*/DEBIAN/*" -exec chmod 644 {} \;

          # Make binary executable
          chmod 755 myapp-deb/usr/local/bin/myapp

          # Keep DEBIAN scripts executable
          chmod 755 myapp-deb/DEBIAN/postinst
          chmod 755 myapp-deb/DEBIAN/prerm

      - name: Build .deb package
        run: |
          # Build the package
          dpkg-deb --build myapp-deb

          # Rename with version info
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
            mv myapp-deb.deb myapp-${VERSION}.deb
          else
            mv myapp-deb.deb myapp-${GITHUB_SHA::7}.deb
          fi

      - name: List built packages
        run: ls -la *.deb

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-deb-package
          path: '*.deb'
          retention-days: 30

      - name: Create Release and Upload .deb
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: '*.deb'
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
